mv number0.png 0.png
mv number1.png 1.png
mv number2.png 2.png
mv number3.png 3.png
mv number4.png 4.png
mv number5.png 5.png
mv number6.png 6.png
mv number7.png 7.png
mv number8.png 8.png
mv number9.png 9.png
